### ISSUE TITLE
Gulp fails to build

### ISSUE THREAD

**Issue by akoutmos** [creativetimofficial/ct-argon-dashboard-pro#14]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

When running `gulp build` I expect the static assets to be compiled and minified.

# Current Behavior

Getting a compilation error.

# Failure Information (for bugs)
```
$ gulp build                                                       
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/home/test/Downloads/argon-dashboard-pro-v1.1.1/node_modules/natives/index.js:143:24)                                                                                        
    at Object.req [as require] (/home/test/Downloads/argon-dashboard-pro-v1.1.1/node_modules/natives/index.js:55:10)                                                                      
    at Object.<anonymous> (/home/test/Downloads/argon-dashboard-pro-v1.1.1/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)                                                     
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
```

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1.Pull down latest version
2. run `npm install`
3. run `$(npm bin)/gulp build`

## Context

* Device: Desktop
* Operating System: Linux
* Browser and Version: NA

**Comment by rarestoma** [comment]
Hi @akoutmos,

Thank you for working with our products. Can you please tell me what version of nodejs are you using? I tested with 10.16.3 and everything is working fine.

All the best,
Rares

**Comment by akoutmos** [comment]
I am on 12.10 at the moment. I rolled back to 11.15 and it seems to work now. Looks like Gulp 3 is not compatible with node 12.*. Thanks for the quick response!
